### ISSUE TITLE
Mod rejected while loging in server.

### ISSUE THREAD

**Issue by recolic** [Cat7373/Anti-AntiCheat-MOD#1]
Server is using AntiCheat 3(ver 3.4.3). My OS := ArchLinux.
I tried to edit mcmod.info but didn't work.

Will AntiAntiCheat support new AntiCheat? AntiCheat client doesn't support Linux/XOS so I have to login to server in this way...

**Comment by recolic** [comment]
Add: mc1.7.10

**Comment by Cat7373** [comment]
这是针对2.x做的，不支持3.x
